# -*- coding: utf-8 -*-
"""HM5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15dtpJdNSgVYopLzR8Gp3SKFkXC4hx4Er
"""

def largestNumber(array):

    if len(array)==1: 
        return str(array[0])
    #convert a list into a string array 
    for i in range(len(array)):
        array[i]=str(array[i])
    # [50,2,1,9]=>['50','2','1','9']
    #find the largest element
    for i in range(len(array)):
        for j in range(i,len(array)):
            if array[j]+array[i]>array[i]+array[j]:
                array[i],array[j]=array[j],array[i]
    #['9', '50', '2', '1']
    #join
    result=''.join(array)
    if(result=='0'*len(result)):
        return '0'
    else:
        return result
         
#input number     
a = [50,2,1,9]
print(largestNumber(a))