# -*- coding: utf-8 -*-
"""Homwork2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ec9xyUPE5EvCppvccSJkAZ_30AFt6pi
"""
import random
N = int(input("How many sticks in the pile: "))
print("There are",N,"sticks in the pile")
Name = input("what is your name: ")
count = 0
while N > 0 :
  print(Name,"How many you will take in the pile: ")
  x = int(input())
  if x > 2 :
    print("No you cannot take more than 2 sticks!")
  elif x < 1 :
    print("No you cannot take more less than 1 stick!")
  elif x > N :
    print("There are no enough stick to take")
  else :
    N = N-x
    count = count +1
    if N == 0 :
      print(Name,", Take the last stick ")
      print("Computer Win! (I, smart computer, It's too easy")
      break
    if N > 0  :
      print("There are", N,"sticks in the pile")
    ##ramdon number
    i = random.randint(1,2)
    if N == 1 :
      i = 1 
    N = N-i
    print("I, Smart computerm takes :", i)
    if N > 0 :
      print("There are", N,"Stick in the pile")
    if N == 0 :
      print("I, smart computer, take the last stick")
      print(Name,", Win! (I, smart computer, am so sad T_T")
      break

