# -*- coding: utf-8 -*-
"""Homwork2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ec9xyUPE5EvCppvccSJkAZ_30AFt6pi
"""
import random
N = int(input("How many sticks in the pile: "))
print("There are",N,"sticks in the pile")
Name = input("what is your name: ")
count = 0
while N > 0 :
  print(Name,"How many you will take in the pile: ")
  x = int(input())
  if x > 2 :
    print("No you cannot take more than 2 sticks!")
  elif x < 1 :
    print("No you cannot take more less than 1 stick!")
  elif x > N :
    print("There are no enough stick to take")
  else :
    N = N-x
    count = count +1
  if N == 0 :
    break
  print("There are", N,"sticks in the pile")

print("OK, There is no stick left in the pile. You spent",count,"times")

